/**
 * CloudPress Admin - Import
 * Replaces WordPress wp-admin/import.php
 * Supports WordPress XML (WXR) import directly.
 * @package CloudPress
 */

import { renderAdminShell } from '../admin-shell.js';
import { hashPassword } from '../../cp-includes/crypto.js';

function esc(str) {
  return String(str ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

export async function handleImport(request, cp) {
  const method = request.method.toUpperCase();
  const prefix = cp.db_prefix || 'cp_';
  let notice   = null;
  let importLog = null;

  if (method === 'POST') {
    const fd     = await request.formData().catch(() => new FormData());
    const action = fd.get('action') || '';

    if (action === 'import_wxr') {
      const file = fd.get('wxr_file');
      if (!file || !file.name) {
        notice = { type: 'error', message: 'Please select a WordPress XML (.xml) export file.' };
      } else {
        try {
          const text   = await file.text();
          const result = await importWXR(cp, prefix, text);
          importLog    = result;
          notice = { type: 'success', message: `Import complete: ${result.posts} posts, ${result.pages} pages, ${result.users} users imported.` };
        } catch (e) {
          notice = { type: 'error', message: `Import failed: ${e.message}` };
        }
      }
    }

    if (action === 'import_json') {
      const file = fd.get('json_file');
      if (!file || !file.name) {
        notice = { type: 'error', message: 'Please select a CloudPress JSON export file.' };
      } else {
        try {
          const text = await file.text();
          const data = JSON.parse(text);
          let posts = 0, users = 0;
          const now  = new Date().toISOString().replace('T',' ').slice(0,19);

          if (Array.isArray(data.posts)) {
            for (const p of data.posts) {
              await cp.db.prepare(
                `INSERT OR IGNORE INTO ${prefix}posts (post_title,post_content,post_status,post_type,post_date,post_modified,post_author,post_name)
                 VALUES (?,?,?,?,?,?,?,?)`
              ).bind(p.post_title||'',p.post_content||'',p.post_status||'draft',p.post_type||'post',
                     p.post_date||now,p.post_modified||now,1,p.post_name||'').run();
              posts++;
            }
          }
          if (Array.isArray(data.users)) {
            for (const u of data.users) {
              const hash = await hashPassword(Math.random().toString(36).slice(2));
              await cp.db.prepare(
                `INSERT OR IGNORE INTO ${prefix}users (user_login,user_pass,user_email,user_registered,user_status,display_name)
                 VALUES (?,?,?,?,0,?)`
              ).bind(u.user_login||'',hash,u.user_email||'',now,u.display_name||u.user_login||'').run();
              users++;
            }
          }
          notice = { type: 'success', message: `JSON import complete: ${posts} posts, ${users} users.` };
        } catch (e) {
          notice = { type: 'error', message: `JSON import failed: ${e.message}` };
        }
      }
    }
  }

  const content = `
<div class="cp-card" style="max-width:720px">
  <h1>Import</h1>
  <p style="color:#666;margin-bottom:24px">Import content from another site into CloudPress.</p>

  <!-- WordPress XML Import -->
  <div style="border:1px solid #ddd;border-radius:8px;padding:20px;margin-bottom:20px">
    <h2 style="margin:0 0 8px;font-size:18px">&#128196; WordPress (WXR)</h2>
    <p style="color:#666;font-size:14px;margin:0 0 16px">Import posts, pages, comments, categories, tags, and users from a WordPress XML export file.</p>
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="action" value="import_wxr">
      <div style="display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap">
        <div style="flex:1;min-width:200px">
          <label style="display:block;margin-bottom:4px;font-weight:500">Choose WordPress export file (.xml)</label>
          <input type="file" name="wxr_file" accept=".xml,text/xml" required
                 style="display:block;width:100%;padding:8px;border:2px dashed #ccc;border-radius:4px;cursor:pointer;box-sizing:border-box">
        </div>
        <button type="submit" class="cp-btn">Import</button>
      </div>
    </form>
  </div>

  <!-- CloudPress JSON Import -->
  <div style="border:1px solid #ddd;border-radius:8px;padding:20px;margin-bottom:20px">
    <h2 style="margin:0 0 8px;font-size:18px">&#128196; CloudPress JSON</h2>
    <p style="color:#666;font-size:14px;margin:0 0 16px">Import from a CloudPress JSON export file (generated by the Export tool).</p>
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="action" value="import_json">
      <div style="display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap">
        <div style="flex:1;min-width:200px">
          <label style="display:block;margin-bottom:4px;font-weight:500">Choose CloudPress export file (.json)</label>
          <input type="file" name="json_file" accept=".json,application/json" required
                 style="display:block;width:100%;padding:8px;border:2px dashed #ccc;border-radius:4px;cursor:pointer;box-sizing:border-box">
        </div>
        <button type="submit" class="cp-btn">Import</button>
      </div>
    </form>
  </div>

  ${importLog ? `
  <div style="background:#f5f5f5;border-radius:6px;padding:16px;margin-top:16px;font-family:monospace;font-size:13px">
    <strong>Import Summary</strong><br>
    Posts: ${importLog.posts ?? 0}<br>
    Pages: ${importLog.pages ?? 0}<br>
    Users: ${importLog.users ?? 0}<br>
    Comments: ${importLog.comments ?? 0}<br>
    Categories: ${importLog.categories ?? 0}<br>
    Tags: ${importLog.tags ?? 0}<br>
    Errors: ${(importLog.errors || []).length}
    ${importLog.errors?.length ? `<br><span style="color:#c00">Errors:<br>${importLog.errors.map(e=>esc(e)).join('<br>')}</span>` : ''}
  </div>` : ''}
</div>`;

  return new Response(
    await renderAdminShell(cp, content, { title: 'Import', notices: notice ? [notice] : [] }),
    { headers: { 'Content-Type': 'text/html; charset=utf-8' } }
  );
}

// -- Minimal WXR parser using regex (no DOM available in Workers) --------------

async function importWXR(cp, prefix, xml) {
  const log = { posts: 0, pages: 0, users: 0, comments: 0, categories: 0, tags: 0, errors: [] };
  const now  = new Date().toISOString().replace('T',' ').slice(0,19);

  function extractTag(str, tag) {
    const m = str.match(new RegExp(`<${tag}(?:[^>]*)><!\\[CDATA\\[([\\s\\S]*?)\\]\\]></${tag}>|<${tag}(?:[^>]*)>([\\s\\S]*?)</${tag}>`, 'i'));
    return m ? (m[1] ?? m[2] ?? '').trim() : '';
  }

  // Categories
  const catMatches = xml.matchAll(/<wp:category>([\s\S]*?)<\/wp:category>/g);
  for (const m of catMatches) {
    try {
      const name = extractTag(m[1], 'wp:cat_name');
      const slug = extractTag(m[1], 'wp:category_nicename');
      if (name) {
        await cp.db.prepare(`INSERT OR IGNORE INTO ${prefix}terms (name,slug,term_group) VALUES (?,?,0)`)
          .bind(name, slug || name.toLowerCase().replace(/\s+/g,'-')).run();
        const term = await cp.db.prepare(`SELECT term_id FROM ${prefix}terms WHERE slug=? LIMIT 1`).bind(slug||name).first();
        if (term) {
          await cp.db.prepare(`INSERT OR IGNORE INTO ${prefix}term_taxonomy (term_id,taxonomy,description,parent,count) VALUES (?,?,?,?,0)`)
            .bind(term.term_id,'category','',0).run();
        }
        log.categories++;
      }
    } catch (e) { log.errors.push(`Category: ${e.message}`); }
  }

  // Tags
  const tagMatches = xml.matchAll(/<wp:tag>([\s\S]*?)<\/wp:tag>/g);
  for (const m of tagMatches) {
    try {
      const name = extractTag(m[1], 'wp:tag_name');
      const slug = extractTag(m[1], 'wp:tag_slug');
      if (name) {
        await cp.db.prepare(`INSERT OR IGNORE INTO ${prefix}terms (name,slug,term_group) VALUES (?,?,0)`)
          .bind(name, slug || name.toLowerCase().replace(/\s+/g,'-')).run();
        const term = await cp.db.prepare(`SELECT term_id FROM ${prefix}terms WHERE slug=? LIMIT 1`).bind(slug||name).first();
        if (term) {
          await cp.db.prepare(`INSERT OR IGNORE INTO ${prefix}term_taxonomy (term_id,taxonomy,description,parent,count) VALUES (?,?,?,?,0)`)
            .bind(term.term_id,'post_tag','',0).run();
        }
        log.tags++;
      }
    } catch (e) { log.errors.push(`Tag: ${e.message}`); }
  }

  // Authors -> users
  const authorMatches = xml.matchAll(/<wp:author>([\s\S]*?)<\/wp:author>/g);
  for (const m of authorMatches) {
    try {
      const login = extractTag(m[1], 'wp:author_login');
      const email = extractTag(m[1], 'wp:author_email');
      const name  = extractTag(m[1], 'wp:author_display_name') || login;
      if (login) {
        const hash = await hashPassword(Math.random().toString(36).slice(2) + Date.now());
        await cp.db.prepare(
          `INSERT OR IGNORE INTO ${prefix}users (user_login,user_pass,user_email,user_registered,user_status,display_name)
           VALUES (?,?,?,?,0,?)`
        ).bind(login, hash, email, now, name).run();
        log.users++;
      }
    } catch (e) { log.errors.push(`Author: ${e.message}`); }
  }

  // Items (posts/pages/attachments)
  const itemMatches = xml.matchAll(/<item>([\s\S]*?)<\/item>/g);
  for (const m of itemMatches) {
    try {
      const itemXml   = m[1];
      const title     = extractTag(itemXml, 'title');
      const content   = extractTag(itemXml, 'content:encoded');
      const excerpt   = extractTag(itemXml, 'excerpt:encoded');
      const status    = extractTag(itemXml, 'wp:status');
      const postType  = extractTag(itemXml, 'wp:post_type');
      const postName  = extractTag(itemXml, 'wp:post_name');
      const postDate  = (extractTag(itemXml, 'wp:post_date') || now).replace('T',' ').slice(0,19);
      const authorLogin = extractTag(itemXml, 'dc:creator');

      if (postType === 'attachment' || postType === 'nav_menu_item') continue;

      let authorId = 1;
      if (authorLogin) {
        const au = await cp.db.prepare(`SELECT ID FROM ${prefix}users WHERE user_login=? LIMIT 1`).bind(authorLogin).first();
        if (au) authorId = au.ID;
      }

      const res = await cp.db.prepare(
        `INSERT INTO ${prefix}posts
           (post_title,post_content,post_excerpt,post_status,post_type,post_name,post_date,post_modified,post_author,comment_status,ping_status)
         VALUES (?,?,?,?,?,?,?,?,?,?,?)`
      ).bind(title,content,excerpt,status||'draft',postType||'post',postName||'',postDate,postDate,authorId,'open','open').run();

      const newPostId = res.meta?.last_row_id;
      if (postType === 'page') log.pages++;
      else log.posts++;

      // Comments
      if (newPostId) {
        const commentMatches = itemXml.matchAll(/<wp:comment>([\s\S]*?)<\/wp:comment>/g);
        for (const cm of commentMatches) {
          try {
            const cx = cm[1];
            await cp.db.prepare(
              `INSERT INTO ${prefix}comments
                 (comment_post_ID,comment_author,comment_author_email,comment_author_url,comment_content,comment_date,comment_approved)
               VALUES (?,?,?,?,?,?,?)`
            ).bind(
              newPostId,
              extractTag(cx,'wp:comment_author'),
              extractTag(cx,'wp:comment_author_email'),
              extractTag(cx,'wp:comment_author_url'),
              extractTag(cx,'wp:comment_content'),
              (extractTag(cx,'wp:comment_date')||now).slice(0,19),
              extractTag(cx,'wp:comment_approved')||'1'
            ).run();
            log.comments++;
          } catch (e) { log.errors.push(`Comment: ${e.message}`); }
        }
      }
    } catch (e) { log.errors.push(`Item: ${e.message}`); }
  }

  return log;
}
